### ISSUE TITLE
Reuse of an old inode after logrotate

### ISSUE THREAD

**Issue by TidamCo** [msimerson/safe-log-reader#26]
I was wondering why my logs didn't get parsed today, turns out I got pretty lucky as the system decided to reuse one of my old file inode after logrotate.

This made it so the reader read the old bookmark and tried to start reading the new log file with a bytesOffset pretty high.

This has a really low chance of happening, but I won't risk it.

I got some ideas for a PR but i'll wait a bit just in case you (the project owner) or someone else has something to say about it !

Ideas :
- in case of a rename, ignore bookmark
- if bookmark bytes > file size, ignore bookmark
- remove old bookmarks when file is done

The second idea might be better as it could be a first step to manage file truncating.

**Comment by msimerson** [comment]
> if bookmark bytes > file size, ignore bookmark

This seems a very prudent course of action.

**Comment by TidamCo** [comment]
But not bulletproofin if the old file was pretty small and the logrotate happens during a big log flood.

**Comment by msimerson** [comment]
There's two things to be aware of. One, the OS may not report events types correctly. IE, that rename event might be a move. Or a truncate. Which is why `renameLinux` attempts to figure it out.

The hazards lie in the semantics of whatever is rotating your log files, your OS, and the behavior of the daemon writing the files (inode following vs file anchoring). Some log rotators (like newsyslog) are exquisitely sane. Others (*cough* rsyslog *cough*) are obtuse.

The event will arrive **very** soon after whatever happened to the file, so it's unlikely that your big log flood is going to happen at the very second a log is being rotated. You can erect a little more safety by only rejecting bookmarks when the new file is substantially smaller than the previous one.

**Comment by TidamCo** [comment]
Seams good to me, i'll try to get that done soon, but this is not a top priority ;)

**Comment by TidamCo** [comment]
I fixed the problem and tested it on my fork.

I also encoutered the "endStream: dampening extra EOF" error quite often on debian 9, but can't reproduce it in the tests. I added a fix that might prevent those, but I will test it in production for a bit before i do a PR !

**Comment by msimerson** [comment]
fixed by #27
